image: mcr.microsoft.com/dotnet/core/sdk:3.0

stages:
  - test
  - release

branch::test:
  stage: test
  except:
    - /master/
  script: |
    dotnet test -v normal /p:CollectCoverage=true

master::release:
  stage: release
  only:
    - /master/
  script: |
    echo ----------------------------------------------- TESTING

    dotnet test -v normal -c Release /p:CollectCoverage=true

    echo ----------------------------------------------- VERSIONING

    SEMVER=`./.3rd/release next-version --bump-patch`
    echo VERSION := $SEMVER
    sed -i -- "s/1\.0\.0\.0/${SEMVER}/g" ./FunctionalLink/FunctionalLink.csproj

    echo ---------------------------------------------- BUILDING

    cd FunctionalLink
    dotnet pack -c Release
    cd ..

    echo ---------------------------------------------- PUBLISHING

    cd ./FunctionalLink/bin/Release
    NUGET_PKG=$(ls *.nupkg)
    echo PACKAGE := $NUGET_PKG
    dotnet nuget push $NUGET_PKG -k $NUGET_KEY -s https://api.nuget.org/v3/index.json
    cd ../../..

    echo ---------------------------------------------- TAGGING

    ./.3rd/release changelog
    ./.3rd/release commit-and-tag CHANGELOG.md FunctionalLink/FunctionalLink.csproj
